# FastBackToLobby Configuration
# 快速返回大厅插件配置

# Lobby server name (BungeeCord/Velocity server name)
# 大厅服务器名称 (BungeeCord/Velocity 服务器名称)
lobby-server: "lobby"

# Language setting (zh_CN, en_US, etc.)
# 语言设置 (zh_CN, en_US 等)
language: "en_US"

# Enable debug mode
# 启用调试模式
debug: false

# Force proxy mode (useful for Velocity without bungeecord: true)
# 强制代理模式 (适用于不需要设置 bungeecord: true 的 Velocity)
force-proxy-mode: false

# Cooldown in seconds (0 to disable)
# 冷却时间（秒）（0为禁用）
cooldown: 3

# Enable sound effect when teleporting
# 传送时启用音效
enable-sound: true

# Sound effect to play
# 播放的音效
sound: "ENTITY_ENDERMAN_TELEPORT"

# Commands that will send player to lobby
# 将玩家发送到大厅的命令
commands:
  - "quit"
  - "l"
  - "lobby"
  - "leave"
  - "hub"

# Note for Velocity users:
# If you're using Velocity and don't want to set bungeecord: true in spigot.yml,
# you can enable 'force-proxy-mode: true' above to bypass proxy detection.
# Velocity 用户注意：
# 如果你使用 Velocity 且不想在 spigot.yml 中设置 bungeecord: true，
# 可以启用上面的 'force-proxy-mode: true' 来绕过代理检测。